version: '3.8'

services:
  dataenv:
    build:
      context: ./dataenv
      dockerfile: Dockerfile
    container_name: dataenv
    volumes:
      - ./dataenv/app:/app
    depends_on:
      - db
    command: tail -f /dev/null

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    container_name: jupyter
    volumes:
      - ./notebooks:/home/jovyan/work
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes

  db:
    image: postgres:latest
    container_name: postgresdb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: