name: Build and Push Docker Images

on:
  push:
    branches:
      - master
    paths:
        - 'dataenv/**'
        - 'jupyter/**'
        - 'db/**'
        - 'docker-compose.yml'
  pull_request:
    branches:
      - master
    paths:
        - 'dataenv/**'
        - 'jupyter/**'
        - 'db/**'
        - 'docker-compose.yml'
  workflow_dispatch:  # Manual trigger

jobs:
  setup:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare cache directory
        run: mkdir -p /tmp/.buildx-cache

  build_dataenv:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push dataenv image
        uses: docker/build-push-action@v3
        with:
          context: ./dataenv
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dataenv:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  build_jupyter:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push jupyter image
        uses: docker/build-push-action@v3
        with:
          context: ./jupyter
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/jupyter:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  build_db:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push db image
        uses: docker/build-push-action@v3
        with:
          context: ./db
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/db:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
