name: Build and Push Docker Images

on:
  push:
    branches:
      - master
    paths:
      - 'dataenv/**'
      - 'jupyter/**'
      - 'db/**'
      - 'docker-compose.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'dataenv/**'
      - 'jupyter/**'
      - 'db/**'
      - 'docker-compose.yml'

jobs:
  build:
    runs-on: self-hosted
    concurrency: 
      group: build-and-push
      cancel-in-progress: true

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build dataenv image
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: ./dataenv
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dataenv:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build jupyter image
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: ./jupyter
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/jupyter:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Build db image
        if: github.event_name == 'push' || github.event_name == 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: ./db
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/db:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
