name: Build and Push Docker Images

on:
  push:
    branches:
      - master
    paths:
      - 'dataenv/**'
      - 'jupyter/**'
      - 'db/**'
      - 'docker-compose.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'dataenv/**'
      - 'jupyter/**'
      - 'db/**'
      - 'docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up .env file
        run: |
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env

      - name: Build and push dataenv image
        uses: docker/build-push-action@v3
        with:
          context: ./dataenv
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dataenv:latest

      - name: Build and push jupyter image
        uses: docker/build-push-action@v3
        with:
          context: ./jupyter
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/jupyter:latest

      - name: Build and push db image
        uses: docker/build-push-action@v3
        with:
          context: ./db
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/db:latest